local_costmap:
  global_frame: odom
  #global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

  update_frequency: 6.0
  publish_frequency: 6.0 
  update_frequency: 4.0
  publish_frequency: 4.0
  rolling_window: true
  width: 2.6
  height: 2.6
  resolution: 0.05

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
