TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map

  acc_lim_x: 1.5  #最大加速度
  acc_lim_theta: 3.3
  max_vel_x: 1.3  #最大速度
  max_vel_x_backwards: 1.1  #最大倒车速度
  max_vel_theta: 2.9
  min_turning_radius: 0.25  #最小转向半径
  is_footprint_dynamic: false
  footprint_model:
    type: "polygon"
    vertices: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]

  yaw_goal_tolerance: 1  #目标角度偏移容忍度
  xy_goal_tolerance: 0.1  
  free_goal_vel: false

  dt_ref: 0.3
  dt_hysteresis: 0.1
  min_samples: 3
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1
  max_global_plan_lookahead_dist: 2.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 3  #检测位姿可到达的时间间隔
  publish_feedback: false
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_backup: true  #当规划器检测到系统异常，允许缩小时域规划范围。
  shrink_horizon_min_duration: 10.0

  min_obstacle_dist: 0.04  #与障碍物的最小期望距离/m
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0  #后方n米范围内的障碍物
  inflation_dist: 0.6  #障碍物周围缓冲区，大于最小期望距离有效
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.05  #w为速度的约束提供缓冲
  weight_acc_lim_x: 1.0  #最大加速度权重 
  weight_acc_lim_theta: 1.0  #最大角加速度权重
  weight_max_vel_x: 100.0  #最大速度权重
  weight_max_vel_theta: 1.0  #最大角速度权重
  weight_kinematics_nh: 1000.0  #运动学的优化权重
  weight_kinematics_forward_drive: 1000.0  #0-1000，数值越大。倒车惩罚越大。
  weight_kinematics_turning_radius: 150.0  #1-1000，越大越容易达到最小转向半径。
  weight_optimaltime: 50  #0-1000 基于轨迹的时间上的权重 0-1000
  weight_obstacle: 50  #优化过程中，和障碍物最小距离的权重 0-1000
  weight_viapoint: 1.0  #优化过程中，和全局路径采样点距离的权重  0-1000
  weight_inflation: 0.1  #优化过程中，膨胀区的权重 0-1000
  weight_adapt_factor: 2.0

  enable_homotopy_class_planning: true
  enable_multithreading: true  #允许多线程并行处理
  max_number_classes: 4  #允许的线程数
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0
